
DROP TABLE IF EXISTS `TODO`;

CREATE TABLE `TODO` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    CONTENT VARCHAR(255),
    STATUS VARCHAR(255), -- READY, RUN, DONE, ABANDONED
    CREATED_AT TIMESTAMP(6) DEFAULT NOW(6),
    REMOVED_AT TIMESTAMP(6)
);
