server:
  port: ${DISCOVERY_SERVER_PORT}

spring:
  application:
    name: discovery-service
    instance_id: ${DISCOVERY_SERVER_NODE_ID:${random.uuid}} # optional value

eureka:
  instance:
    hostname: ${DISCOVERY_SERVER_HOSTNAME}
    instance-id: ${spring.application.instance_id}

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_PEERING_URLS}
