-- define init data

CREATE TABLE `test`.TODO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    CONTENT VARCHAR(255),
    STATUS VARCHAR(255),
    CREATED_AT TIMESTAMP(6) DEFAULT NOW(6),
    REMOVED_AT TIMESTAMP(6) DEFAULT NULL
);
